_wandb:
    value:
        cli_version: 0.28.2
        e:
            wkxnpnu43goag1wniqs17g70daa5cpfe:
                args:
                    - --exp_name
                    - SEAN-Net
                    - --data_list
                    - configs/data_list.csv
                    - --audio_path
                    - /scratch_nvme/VoxCeleb2-2Mix/audio_clean/train/
                    - --visual_path
                    - /home/ale/datasets/VoxCeleb2-2Mix_SEANNet/
                    - --backbone
                    - seanet
                    - --n_cpu
                    - "20"
                    - --length
                    - "4"
                    - --batch_size
                    - "8"
                    - --max_epoch
                    - "150"
                    - --lr
                    - "0.00100"
                    - --grad_accum_steps
                    - "1"
                    - --compile
                    - --tf32
                    - --precision
                    - bf16
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "501809635328"
                        used: "276780126208"
                email: amarchei@iis.ee.ethz.ch
                executable: /home/ale/miniconda3/envs/swiftnet/bin/python
                git:
                    commit: 269ab9c67504ff2c4e07404fbd89be2a19f65000
                    remote: https://github.com/TaoRuijie/SEANet.git
                gpu: NVIDIA GeForce RTX 5060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 4608
                      memoryTotal: "17103323136"
                      name: NVIDIA GeForce RTX 5060 Ti
                      uuid: GPU-9738389e-a3e9-40c9-e30e-4e765906bf8e
                host: potentia
                memory:
                    total: "33524101120"
                os: Linux-7.0.0-31-generic-x86_64-with-glibc2.39
                program: /home/ale/work/av-tse/SEANet/main.py
                python: CPython 3.10.20
                root: runs/SEAN-Net
                startedAt: "2026-09-17T19:41:38.208795Z"
                writerId: wkxnpnu43goag1wniqs17g70daa5cpfe
        m:
            - "1": epoch
              "6":
                - 3
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": val/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": system/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 7
                - 13
                - 16
            "4": 3.10.20
            "5": 0.28.2
            "12": 0.28.2
            "13": linux-x86_64
alpha:
    value: 0.1
backbone:
    value: seanet
batch_size:
    value: 8
compile_mode:
    value: default
length:
    value: 4
lr:
    value: 0.001
lr_decay:
    value: 0.97
max_epoch:
    value: 150
n_cpu:
    value: 20
precision:
    value: bf16
tf32:
    value: true
torch_compile:
    value: true
val_step:
    value: 3
